name: ppi 
channels:
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - python=3.9
    - pip
    - numpy
    - numpy-base
    - matplotlib
    - matplotlib-base
    - scipy
    - scikit-image
    - pytorch
    - torchvision
    - torchaudio
    - pandas
    - seaborn
    - scikit-learn
    - tqdm
#    - cudatoolkit=11.6
    - ipykernel
    - jupyter
    - xgboost
    - seaborn>=0.12.0
    - geopandas
    - geoplot
    - hyperopt
    - pip:
      - folktables
      - alphashape
      - threadpoolctl==3.1.0
      - 'zoobot[pytorch]'
